---
dependencies: []

galaxy_info:
  role_name: logstash
  author: express42
  description: Logstash setup for DevOpsEvents.
  company: "Express 42, LLC"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
