---
dependencies: []

galaxy_info:
  role_name: java
  author: express42
  description: Java for Linux
  company: "Express 42, LLC"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
        - focal
    - name: FreeBSD
      versions:
        - 10.2
